development:
  adapter: postgresql
  encoding: unicode
  database: get_tickets_development
  pool: 5
  username: marcushoile
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: get_tickets_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: get_tickets_production
  pool: 5
  username: 
  password:
